import { createSlice } from '@reduxjs/toolkit';

const initialState = {
  search: '',
  sortBy: 'title',
  order: 'asc',
  page: 1,
};

const filterSlice = createSlice({
  name: 'filters',

  initialState,

  reducers: {
    setSearch: (state, action) => {
      state.search = action.payload;
      state.page = 1;
    },

    setSort: (state, action) => {
      state.sortBy = action.payload.sortBy;
      state.order = action.payload.order;
      state.page = 1;
    },

    setPage: (state, action) => {
      state.page = action.payload;
    },
  },
});

export const { setSearch, setSort, setPage } = filterSlice.actions;

export default filterSlice.reducer;

// This will be generated by `createSlice`

// const filterSlice = {
//   name: "filters",

//   actions: {
//     setSearch: (value) => ({
//       type: "filters/setSearch",
//       payload: value,
//     }),

//     setSort: (value) => ({
//       type: "filters/setSort",
//       payload: value,
//     }),

//     setPage: (value) => ({
//       type: "filters/setPage",
//       payload: value,
//     }),
//   },

//   reducer: (state = initialState, action) => {
//     switch (action.type) {
//       case "filters/setSearch":
//         return {
//           ...state,
//           search: action.payload,
//           page: 1,
//         };

//       case "filters/setSort":
//         return {
//           ...state,
//           sortBy: action.payload.sortBy,
//           order: action.payload.order,
//           page: 1,
//         };

//       case "filters/setPage":
//         return {
//           ...state,
//           page: action.payload,
//         };

//       default:
//         return state;
//     }
//   },
// };
